// Feed list sourced from https://github.com/mr-r3b00t/cyber_rss
// Broken feeds removed after live testing (cyber.gov.au, checkpoint, rapid7, google TAG, ZDI blog)
const FEEDS = [
  {name:"CERT-FR (ANSSI)",                url:"https://www.cert.ssi.gouv.fr/feed/",                                         category:"cert"},
  {name:"CISA Cybersecurity Advisories",  url:"https://www.cisa.gov/cybersecurity-advisories/all.xml",                      category:"cert"},
  {name:"CISA ICS Advisories",            url:"https://www.cisa.gov/cybersecurity-advisories/ics-advisories.xml",           category:"cert"},
  {name:"CISA ICS Medical Advisories",    url:"https://www.cisa.gov/cybersecurity-advisories/ics-medical-advisories.xml",   category:"cert"},
  {name:"JPCERT/CC",                      url:"https://www.jpcert.or.jp/english/rss/jpcert-en.rdf",                         category:"cert"},
  {name:"JPCERT/CC Blog",                 url:"https://blogs.jpcert.or.jp/en/atom.xml",                                     category:"cert"},
  {name:"UK NCSC All",                    url:"https://www.ncsc.gov.uk/api/1/services/v1/all-rss-feed.xml",                 category:"cert"},
  {name:"UK NCSC Guidance",               url:"https://www.ncsc.gov.uk/api/1/services/v1/guidance-rss-feed.xml",            category:"cert"},
  {name:"UK NCSC News",                   url:"https://www.ncsc.gov.uk/api/1/services/v1/news-rss-feed.xml",                category:"cert"},
  {name:"UK NCSC Reports",                url:"https://www.ncsc.gov.uk/api/1/services/v1/report-rss-feed.xml",              category:"cert"},
  {name:"Bleeping Computer (forum)",      url:"https://www.bleepingcomputer.com/forum45.xml",                               category:"news"},
  {name:"BleepingComputer",               url:"https://www.bleepingcomputer.com/feed/",                                     category:"news"},
  {name:"CyberScoop",                     url:"https://www.cyberscoop.com/feed",                                            category:"news"},
  {name:"Dark Reading",                   url:"https://www.darkreading.com/rss.xml",                                        category:"news"},
  {name:"Intelligence Online",            url:"https://feeds.feedburner.com/IntelligenceOnline",                            category:"news"},
  {name:"Krebs on Security",              url:"https://krebsonsecurity.com/feed/",                                          category:"news"},
  {name:"Risky Business Podcast",         url:"https://risky.biz/rss.xml",                                                 category:"news"},
  {name:"Schneier on Security",           url:"https://www.schneier.com/feed/atom/",                                        category:"news"},
  {name:"SecurityWeek",                   url:"https://feeds.feedburner.com/securityweek",                                  category:"news"},
  {name:"The Hacker News",                url:"https://feeds.feedburner.com/TheHackersNews",                                category:"news"},
  {name:"The Record",                     url:"https://therecord.media/feed/",                                              category:"news"},
  {name:"CVEfeed.io",                     url:"https://cvefeed.io/rssfeed/latest.xml",                                     category:"vulnerability"},
  {name:"FortiGuard PSIRT",               url:"https://www.fortiguard.com/rss/ir.xml",                                     category:"vulnerability"},
  {name:"Microsoft Security Updates",     url:"https://api.msrc.microsoft.com/update-guide/rss",                           category:"vulnerability"},
  {name:"Palo Alto Security Advisories",  url:"https://security.paloaltonetworks.com/rss.xml",                             category:"vulnerability"},
  {name:"Qualys Blog",                    url:"https://blog.qualys.com/feed",                                              category:"vulnerability"},
  {name:"Apple Developer Releases",       url:"https://developer.apple.com/news/releases/rss/releases.rss",                category:"vendor_advisory"},
  {name:"Apple Newsroom",                 url:"https://www.apple.com/newsroom/rss-feed.rss",                               category:"vendor_advisory"},
  {name:"Cisco Security Blog",            url:"https://blogs.cisco.com/security/feed",                                     category:"vendor_advisory"},
  {name:"Cisco Talos Intelligence",       url:"https://feeds.feedburner.com/feedburner/Talos",                             category:"vendor_blog"},
  {name:"Elastic Security Labs",          url:"https://www.elastic.co/security-labs/rss/feed.xml",                        category:"vendor_blog"},
  {name:"Fortinet Threat Research",       url:"https://feeds.fortinet.com/fortinet/blog/psirt",                            category:"vendor_blog"},
  {name:"Mandiant Blog",                  url:"https://www.mandiant.com/resources/blog/rss.xml",                           category:"vendor_blog"},
  {name:"Proofpoint Threat Insight",      url:"https://www.proofpoint.com/us/threat-insight-blog.xml",                    category:"vendor_blog"},
  {name:"SentinelOne / SentinelLabs",     url:"https://www.sentinelone.com/feed/",                                        category:"vendor_blog"},
  {name:"Google Online Security Blog",    url:"https://feeds.feedburner.com/GoogleOnlineSecurityBlog",                     category:"malware_research"},
  {name:"Google Project Zero",            url:"https://googleprojectzero.blogspot.com/feeds/posts/default?alt=rss",        category:"malware_research"},
  {name:"Malwarebytes Labs",              url:"https://blog.malwarebytes.com/feed/",                                       category:"malware_research"},
  {name:"Securelist (Kaspersky)",         url:"https://securelist.com/feed/",                                              category:"malware_research"},
  {name:"WeLiveSecurity (ESET)",          url:"https://www.welivesecurity.com/en/rss/feed/",                               category:"malware_research"},
  {name:"Exploit-DB",                     url:"https://www.exploit-db.com/rss.xml",                                       category:"exploit_research"},
  {name:"ZDI Published Advisories",       url:"https://www.zerodayinitiative.com/rss/published/",                         category:"exploit_research"},
  {name:"ZDI Upcoming Advisories",        url:"https://www.zerodayinitiative.com/rss/upcoming/",                          category:"exploit_research"},
  {name:"SANS ISC Diary",                 url:"https://isc.sans.edu/rssfeed.xml",                                         category:"community"},
  {name:"SANS ISC Diary (Full)",          url:"https://isc.sans.edu/rssfeed_full.xml",                                    category:"community"},
];
